easy_admin:
    entities:
        # List the entity class name you want to manage
        Admin:
            class: DrkDD\Pflegefinder\Entity\Admin
            form:
                fields:
                    - { property: 'plainPassword' , type: 'password'}
            new:
                fields:
                    - 'username'
                    - { property: 'plainPassword' , type: 'password', type_options: {required: true}}
        Pflegeheim:
            class: DrkDD\Pflegefinder\Entity\Pflegeheim
            list:
                fields:
                    - 'id'
                    - 'name'
                    - 'city'
                    - 'postalCode'
                    - 'street'
                    - 'contactPerson'
                    - 'maxContacts'
                    - 'vermittelteKontakte'
        User:
            class: DrkDD\Pflegefinder\Entity\User
            form:
                fields:
                    - 'name'
                    - 'email'
                    - 'postalCode'
                    - property: 'age'
                      label: 'Altersgruppe'
                      type: choice
                      type_options:
                        choices:
                            '<6': 0
                            '6-12': 1
                            '13-16': 2
                            '17-27': 3
                            '>27': 4
                        placeholder: 'leer'
            list:
                fields:
                    - 'name'
                    - 'email'
                    - 'postalCode'
                    - 'altersGruppe'
