version: '3.6'

services:
  db:
    image: 'mariadb'
    environment:
      - 'MYSQL_ROOT_PASSWORD=yahJieNoip1geihu'
      - 'MYSQL_DATABASE=drk'
      - 'MYSQL_USER=drk'
      - 'MYSQL_PASSWORD=aiZie9eereek2que'
    ports:
      - '13306:3306'
  php:
    build: '.'
    depends_on:
      - 'db'
    ports:
      - '80:80'
    volumes:
      - '.:/var/www/html'