version: '3.7'

services:
  db:
    image: 'mariadb'
    environment:
      - 'MYSQL_ROOT_PASSWORD=yahJieNoip1geihu'
      - 'MYSQL_DATABASE=drk'
      - 'MYSQL_USER=drk'
      - 'MYSQL_PASSWORD=aiZie9eereek2que'
    ports:
      - '13306:3306'
  mail:
    image: 'mailhog/mailhog'
    environment:
      - 'MH_HOSTNAME=mail'
    ports:
      - '81:8025'
  php:
    build: 'docker/php'
    depends_on:
      - 'db'
      - 'mail'
      - 'www'
    volumes:
      - '.:/var/www'
  www:
    build: 'docker/www'
    ports:
      - '80:80'
    volumes:
      - '.:/var/www'